# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
    ]
