# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20160828_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=40, verbose_name='Slug'),
        ),
    ]
