# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20160828_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Slug'),
        ),
    ]
